### ISSUE TITLE
It does not WORK when it finds tweets and wants to comment

### ISSUE THREAD

**Issue by Trimolo** [CryptoFoxDev/CryptoGiveawayBot#1]
[GiveawayBot] Retweeted the tweet
[GiveawayBot] Posting comment:
Traceback (most recent call last):
  File "C:\Users\Miller Biller\Desktop\no gui\bot-no-gui.py", line 198, in <module>
    checkTweets()
  File "C:\Users\Miller Biller\Desktop\no gui\bot-no-gui.py", line 180, in checkTweets
    joinGiveaway(tweet)
  File "C:\Users\Miller Biller\Desktop\no gui\bot-no-gui.py", line 152, in joinGiveaway
    api.update_status(status=comment, in_reply_to_status_id=tweet.get('id') , auto_populate_reply_metadata=True)
  File "C:\Users\Miller Biller\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\Miller Biller\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\api.py", line 1136, in update_status
    return self.request(
  File "C:\Users\Miller Biller\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\api.py", line 259, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden
170 - Missing required parameter: status.

**Comment by Trimolo** [comment]
Also, another problem it has is that it just tweets any thing that has ETH or crypto tags, even if the account  or the tweet it is tweeting has 3 to 5 retweets and is scam.

so, is there a way to change what keywords or tags it needs to consider a giveaway ? + checking if the tweet has more retweets prior to me retweeting ?

**Comment by mario-to-lowercase** [comment]
Thanks for you submission.
I will check and try to fix it in the next few days.
